### ISSUE TITLE
Choosing a course for imagemapster.js

### ISSUE THREAD

**Issue by pbchase** [ctsit/imagemap#16]
@123andy, the most recent issue on the imagemap module, issue #14, exposed us to an unpleasant aspect of the imagemapster.js library: it is somewhat rudderless. The authoritative repo, https://github.com/jamietre/ImageMapster, has 150 open issues, PRs that haven't been serviced in years, and two years have passed since the last commit. @marlycormar found the fix to the REDCap 8.7.1 issue on a fork of the ImageMapster repo, specifically, https://github.com/davintoo/ImageMapster. 

I feel like we should follow an authoritative repo for included libraries and simply include that "official" version of the library rather than make one-off fixes as Marly did to fix issue #14, but "official" is nebulous in this case. My inkling is to go with davintoo's fork and document that we use that fork. In lieu of tagged releases, we could reference the commit ID of the code we copied.

What do you think?

**Comment by 123andy** [comment]
Go for it.  Like so many things - I was just trying to solve one problem for one project many years ago and it grew…

-A


On Aug 30, 2018, at 11:03 AM, Philip Chase <notifications@github.com<mailto:notifications@github.com>> wrote:


@123andy<https://github.com/123andy>, the most recent issue on the imagemap module, issue #14<https://github.com/ctsit/imagemap/issues/14>, exposed us to an unpleasant aspect of the imagemapster.js library: it is somewhat rudderless. The authoritative repo, https://github.com/jamietre/ImageMapster, has 150 open issues, PRs that haven't been serviced in years, and two years. @marlycormar<https://github.com/marlycormar> found the fix to the REDCap 8.7.1 issue on a fork of the ImageMapster repo, specifically, https://github.com/davintoo/ImageMapster.

I feel like we should follow an authoritative repo for included libraries and simply include that "official" version of the library rather than make one-off fixes as Marly did to fix issue #14<https://github.com/ctsit/imagemap/issues/14>, but "official" is nebulous in this case. My inkling is to go with davintoo's fork and document that we use that fork. In lieu of tagged releases, we could reference the commit ID of the code we copied.

What do you think?

**Comment by pbchase** [comment]
Addressed by PR #27
