### ISSUE TITLE
Body Map Module 

### ISSUE THREAD

**Issue by Ritacca** [ctsit/imagemap#56]
Hi, 

I am having problems with the body map (Image Map v1.6.0). We are using REDCap version 10.2.3. The body map is in two different instruments. When they are sent out as surveys, the body map does not appear. I tried troubleshooting on various devices and from different browsers. When sent out as a survey, the image does not work. When I am logged into REDCap as an administrator, and open the survey, the body map appears. I have spoken to the REDCap Team at my institution (University of Toronto) but they were not able to help as this is an external module they are not familiar with. 

Thank you for your help.

**Comment by Ritacca** [comment]
Branching logic is used when participants select gender (male, female, unknown). The corresponding body map should appear according to the gender that is selected.

**Comment by 123andy** [comment]
@Ritacca - what kind of authentication does your server use?    One guess is that you are using shibboleth and that you do not have the 'use api urls' checked in the module configuration (which is at the SYSTEM level - meaning you have to goto control center, then external modules, then settings.)

If you send us one of the public survey links, we can confirm, but I'm guessing that if you use a browser that is not authenticated to REDCap, turn on your 'debugger mode' (chrome in the picture below), click on preserve log, then refresh the survey, you will see that one of your js include files does NOT return a 200 status code because it is getting blocked at your server.

![image](https://user-images.githubusercontent.com/7461553/104522053-05381300-55b3-11eb-991c-5643907ba102.png)

**Comment by 123andy** [comment]
This should be resolved with the new option for using api urls if you have shib and don't use query-string parsing for noauth.

**Comment by mbentz-uf** [comment]
Addressed by PR #61.
